language: node_js

env:
  global:
    - HOST=0.0.0.0

cache:
  yarn: false
  directories:
    - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn install --frozen-lockfile

matrix:
  include:
    - node_js: '8.10'
      name: 'Test on Node.js 8.10'
      if: branch =~ /(master|staging|trying|v\d+\.x)/
      before_script:
        - 'yarn lint'
      script: 'yarn test --maxWorkers=2 --ci'
    - node_js: '10'
      name: 'Test on Node.js 10'
      before_script:
        - 'yarn lint'
      script: 'yarn test --maxWorkers=2 --ci'
    - node_js: 'lts/*'
      name: 'Canarist test on Node.js lts/*'
      if: branch =~ /(master|staging|trying|v\d+\.x)/
      script: 'yarn canarist'
