language: node_js

cache:
  yarn: false
  directories:
    - node_modules

before_install:
  - npm i -g yarn@latest

env:
  global:
    - HOST=0.0.0.0

install:
  - yarn install --frozen-lockfile

matrix:
  include:
    - node_js: '10.13'
      name: 'Test on Node.js 10'
      if: branch =~ /(master|staging|trying|v\d+\.x)/
      script: 'yarn test --maxWorkers=2 --ci'
      env:
        - CACHE_NAME=node-v10
    - node_js: '12.13'
      name: 'Test on Node.js 12'
      if: branch =~ /(master|staging|trying|v\d+\.x)/
      script: 'yarn test --maxWorkers=2 --ci'
      env:
        - CACHE_NAME=node-v12
    - node_js: '13'
      name: 'Test on Node.js 13 (latest)'
      before_script:
        - 'yarn lint'
      script: 'yarn test --maxWorkers=2 --ci'
      env:
        - CACHE_NAME=node-v13
    - node_js: 'lts/*'
      name: 'Canarist test on Node.js latest lts'
      if: branch =~ /(master|staging|trying|v\d+\.x)/
      script: 'yarn canarist'
      env:
        - CACHE_NAME=canary
